<template>
  <div>
    <Dialog
      :show="dialogConfig.show"
      :title="dialogConfig.title"
      :buttons="dialogConfig.buttons"
      width="600px"
      :showCancel="showCancel"
      @close="dialogConfig.show = false"
    >
      <el-form
        :model="formData"
        :rules="rules"
        ref="formDataRef"
        label-width="100px"
        @submit.prevent
      >
        <el-form-item label="file"> {{ formData.fileName }} </el-form-item>
        <template v-if="showType == 0">
          <el-form-item label="valid period" prop="validType">
            <el-radio-group v-model="formData.validType">
              <el-radio :label="0">1 day</el-radio>
              <el-radio :label="1">7 days</el-radio>
              <el-radio :label="2">30 days</el-radio>
              <el-radio :label="3">forever</el-radio>
            </el-radio-group>
          </el-form-item>
          <el-form-item label="share code" prop="codeType">
            <el-radio-group v-model="formData.codeType">
              <el-radio :label="0">custom</el-radio>
              <el-radio :label="1">generated by system</el-radio>
            </el-radio-group>
          </el-form-item>
          <el-form-item prop="code" v-if="formData.codeType == 0">
            <el-input
              clearable
              placeholder="Please enter share code"
              v-model.trim="formData.code"
              maxLength="5"
              :style="{ width: '130px' }"
            ></el-input>
          </el-form-item>
        </template>
        <template v-else>
          <el-form-item label="share link">
            {{ shareUrl }}{{ resultInfo.shareId }}
          </el-form-item>
          <el-form-item label="share code">
            {{ resultInfo.code }}
          </el-form-item>
          <el-form-item>
            <el-button type="primary" @click="copy">copy link and share code</el-button>
          </el-form-item>
        </template>
      </el-form>
    </Dialog>
  </div>
</template>

<script setup>
import useClipboard from "vue-clipboard3";
const { toClipboard } = useClipboard();
import { ref, getCurrentInstance, nextTick } from "vue";
const { proxy } = getCurrentInstance();

const shareUrl = ref(document.location.origin + "/share/");

const api = {
  shareFile: "/share/shareFile",
};
const showType = ref(0);
const formData = ref({});
const formDataRef = ref();
const rules = {
  validType: [{ required: true, message: "Please select validity period" }],
  codeType: [{ required: true, message: "Please select the type of share code" }],
  code: [
    { required: true, message: "Please enter share code" },
    { validator: proxy.Verify.shareCode, message: "Share code can only be numbers" },
    { min: 5, message: "share code consists of no less than 5 digits" },
  ],
};

const showCancel = ref(true);
const dialogConfig = ref({
  show: false,
  title: "share",
  buttons: [
    {
      type: "primary",
      text: "confirm",
      click: (e) => {
        share();
      },
    },
  ],
});

const resultInfo = ref({});
const share = async () => {
  if (Object.keys(resultInfo.value).length > 0) {
    dialogConfig.value.show = false;
    return;
  }
  formDataRef.value.validate(async (valid) => {
    if (!valid) {
      return;
    }
    let params = {};
    Object.assign(params, formData.value);
    let result = await proxy.Request({
      url: api.shareFile,
      params: params,
    });
    if (!result) {
      return;
    }
    showType.value = 1;
    resultInfo.value = result.data;
    dialogConfig.value.buttons[0].text = "close";
    showCancel.value = false;
  });
};

const show = (data) => {
  showCancel.value = true;
  dialogConfig.value.show = true;
  showType.value = 0;
  resultInfo.value = {};
  nextTick(() => {
    formDataRef.value.resetFields();
    formData.value = Object.assign({}, data);
  });
};

defineExpose({ show });

const copy = async () => {
  await toClipboard(
    `link:${shareUrl.value}${resultInfo.value.shareId} share code : ${resultInfo.value.code}`
  );
  proxy.Message.success("copy successfully");
};
</script>

<style lang="scss" scoped>
</style>
